// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1PFFjFfxSzGSEKV_KTABINeOtRM8ZuNY',
    appId: '1:751398151035:web:3b4148b37ff2109adf93de',
    messagingSenderId: '751398151035',
    projectId: 'shoppingapp-d0a5f',
    authDomain: 'shoppingapp-d0a5f.firebaseapp.com',
    databaseURL: 'https://shoppingapp-d0a5f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shoppingapp-d0a5f.appspot.com',
    measurementId: 'G-CFDPNY4797',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDc8uLORGk4Chlz010BRZPuYvbtT_qUC10',
    appId: '1:751398151035:android:fa36907b68b32331df93de',
    messagingSenderId: '751398151035',
    projectId: 'shoppingapp-d0a5f',
    databaseURL: 'https://shoppingapp-d0a5f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shoppingapp-d0a5f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbfbyQ9UQpPMT2Zaru6QBxNAgqRbCIO54',
    appId: '1:751398151035:ios:1f0f0196279be73fdf93de',
    messagingSenderId: '751398151035',
    projectId: 'shoppingapp-d0a5f',
    databaseURL: 'https://shoppingapp-d0a5f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shoppingapp-d0a5f.appspot.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbfbyQ9UQpPMT2Zaru6QBxNAgqRbCIO54',
    appId: '1:751398151035:ios:1f0f0196279be73fdf93de',
    messagingSenderId: '751398151035',
    projectId: 'shoppingapp-d0a5f',
    databaseURL: 'https://shoppingapp-d0a5f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shoppingapp-d0a5f.appspot.com',
    iosBundleId: 'com.example.shoppingApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1PFFjFfxSzGSEKV_KTABINeOtRM8ZuNY',
    appId: '1:751398151035:web:3ea06d7a03fc7223df93de',
    messagingSenderId: '751398151035',
    projectId: 'shoppingapp-d0a5f',
    authDomain: 'shoppingapp-d0a5f.firebaseapp.com',
    databaseURL: 'https://shoppingapp-d0a5f-default-rtdb.europe-west1.firebasedatabase.app',
    storageBucket: 'shoppingapp-d0a5f.appspot.com',
    measurementId: 'G-FGL7Y2X9WF',
  );
}
